In [3]:
import xarray as xr
import rioxarray as rxr
import rasterio
import glob
import geopandas as gpd
from tqdm import tqdm_notebook
import pandas as pd
from rasterstats import zonal_stats

import sys
sys.path.append("D:\Work\WB\LDT\src")
from dhelper import get_daterange

In [2]:
paths = glob.glob(r"D:\Work\WB\LDT\countries\BTN\raw_data/temperature/*.nc")
ds1 = xr.open_dataset(paths[0]).drop_vars("expver", errors="ignore")
ds2 = xr.open_dataset(paths[1]).drop_vars("expver", errors="ignore")
ds3 = xr.open_dataset(paths[2]).drop_vars("expver", errors="ignore")
ds4 = xr.open_dataset(paths[3]).drop_vars("expver", errors="ignore")

temperature = xr.concat([ds1, ds2, ds3, ds4], dim="valid_time")  # Change 'time' to your target dimension

ds1.close()
ds2.close()
ds3.close()
ds4.close()


paths = glob.glob(r"D:\Work\WB\LDT\countries\BTN\raw_data/precipitation/*.nc")
ds1 = xr.open_dataset(paths[0]).drop_vars("expver", errors="ignore")
ds2 = xr.open_dataset(paths[1]).drop_vars("expver", errors="ignore")
ds3 = xr.open_dataset(paths[2]).drop_vars("expver", errors="ignore")
ds4 = xr.open_dataset(paths[3]).drop_vars("expver", errors="ignore")

precipitation = xr.concat([ds1, ds2, ds3, ds4], dim="valid_time")  # Change 'time' to your target dimension

ds1.close()
ds2.close()
ds3.close()
ds4.close()

affine = rasterio.open(paths[0]).transform

In [3]:
# affine = rasterio.open(r"D:\Work\WB\LDT\countries\BTN\raw_data\temperature\temperature.nc").transform
# temp = rxr.open_rasterio(r"D:\Work\WB\LDT\countries\BTN\raw_data\temperature\temperature.nc")
# prec = rxr.open_rasterio(r"D:\Work\WB\LDT\countries\BTN\raw_data\precipitation\precipitation.nc")

In [21]:
admin = 1
poly = gpd.read_file(rf"D:\Work\WB\LDT\countries\BTN\shapefiles/gadm41_BTN_{admin}.json")
poly = poly[[f'GID_{admin}', 'geometry']]

dates = []
dates.extend(get_daterange('2000-01-01', '2010-12-31', input_format='%Y-%m-%d', output_format='%Y-%m-%d'))
dates.extend(get_daterange('2018-01-01', '2024-12-31', input_format='%Y-%m-%d', output_format='%Y-%m-%d'))

In [22]:
poly_lst = list()

for day in tqdm_notebook(dates):
    
    df_poly = poly.copy(deep=True)
    df_poly['date'] = day
    
    temp_day = temperature.sel(valid_time=day)
    prec_day = precipitation.sel(valid_time=day)

    avg_temp_day = temp_day.mean(dim='valid_time')
    max_temp_day = temp_day.max(dim='valid_time')
    total_prec_day = prec_day.sum(dim='valid_time')

    avg_temp_zonal = zonal_stats(df_poly.geometry,
                                 avg_temp_day['t2m'].values, 
                                 affine=affine,
                                 stats=['mean'],
                                 nodata=0)
    
    max_temp_zonal = zonal_stats(poly.geometry,
                                 max_temp_day['t2m'].values, 
                                 affine=affine,
                                 stats=['max'],
                                 nodata=0)
    
    total_prec_zonal = zonal_stats(poly.geometry,
                                 total_prec_day['tp'].values, 
                                 affine=affine,
                                 stats=['sum'],
                                 nodata=0)
    
    df_avg = pd.DataFrame(avg_temp_zonal)
    df_max = pd.DataFrame(max_temp_zonal)
    df_prec = pd.DataFrame(total_prec_zonal)

    df_poly['average_temperature'] = df_avg['mean']
    df_poly['max_temperature'] = df_max['max']
    df_poly['precipitation'] = df_prec['sum']

    poly_lst.append(df_poly)

C:\Users\sonle\AppData\Local\Temp\ipykernel_36672\2918308148.py:3: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for day in tqdm_notebook(dates):

  0%|          | 0/6575 [00:00<?, ?it/s]

In [23]:
full_df = pd.concat(poly_lst, axis=0)
# full_df = full_df.rename({'avg_temp': 'average_temperature',
#                           'max_temp': 'max_temperature'}, axis=1)
full_df['average_temperature'] = full_df['average_temperature'] - 273.15
full_df['max_temperature'] = full_df['max_temperature'] - 273.15
full_df

,GID_1,geometry,date,average_temperature,max_temperature,precipitation
0,BTN.1_1,"MULTIPOLYGON (((90.984 27.5562, 90.9865 27.553...",2000-01-01,-8.049251,6.099268,0.000473
1,BTN.2_1,"MULTIPOLYGON (((89.7375 26.7605, 89.7384 26.75...",2000-01-01,7.345544,16.235986,0.000627
2,BTN.3_1,"MULTIPOLYGON (((89.7383 26.7697, 89.7404 26.77...",2000-01-01,9.507990,20.871973,0.000956
3,BTN.4_1,"MULTIPOLYGON (((89.7318 27.7505, 89.7359 27.74...",2000-01-01,-12.567529,-2.838232,0.000119
4,BTN.5_1,"MULTIPOLYGON (((89.3421 27.211, 89.3419 27.206...",2000-01-01,-1.426245,8.647119,0.000960
...,...,...,...,...,...,...
15,BTN.15_1,"MULTIPOLYGON (((91.5207 27.0229, 91.5203 27.02...",2024-12-31,4.763116,15.400293,0.001283
16,BTN.16_1,"MULTIPOLYGON (((90.5957 27.4579, 90.605 27.452...",2024-12-31,1.426263,13.202539,0.001085
17,BTN.17_1,"MULTIPOLYGON (((90.044 26.827, 90.0358 26.8249...",2024-12-31,NaN,NaN,NaN
18,BTN.18_1,"MULTIPOLYGON (((90.0681 27.1163, 90.0482 27.13...",2024-12-31,3.386641,12.995996,0.005160
19,BTN.20_1,"MULTIPOLYGON (((91.0721 26.8703, 91.0612 26.86...",2024-12-31,10.077743,19.872461,0.000376

In [24]:
full_df[[f'GID_{admin}', 'date', 'average_temperature']].to_csv(rf"D:\Work\WB\LDT\countries\BTN\datasets\admin_{admin}/avg_temp.csv", index=False)
full_df[[f'GID_{admin}', 'date', 'max_temperature']].to_csv(rf"D:\Work\WB\LDT\countries\BTN\datasets\admin_{admin}/max_temp.csv", index=False)
full_df[[f'GID_{admin}', 'date', 'precipitation']].to_csv(rf"D:\Work\WB\LDT\countries\BTN\datasets\admin_{admin}/precipitation.csv", index=False)

In [8]:
poly = gpd.read_file('D:\Work\WB\LDT\countries\SRB\shapefiles\gadm41_SRB_0.json')
poly.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [ ]:
shapefile_path = 'D:\Work\WB\LDT\countries\SRB\shapefiles\gadm41_SRB_0.json'
nc_file_path = r"D:\Work\WB\LDT\data\raw_data\gfdl-esm4_r1i1p1f1_w5e5_ssp585_tasmax_global_daily_2015_2020.nc"

files = glob.glob("D:/Work/WB\LDT/data/raw_data/*.nc")

# Load the shapefile as a GeoDataFrame
gdf = gpd.read_file(shapefile_path)

for file in tqdm_notebook(files):
    # Open the NetCDF dataset using xarray with rioxarray extension
    ds = xr.open_dataset(file)

    # Assign CRS and use rioxarray for spatial operations
    ds.rio.set_spatial_dims(x_dim="lon", y_dim="lat", inplace=True)
    ds.rio.write_crs("EPSG:4326", inplace=True)

    # Clip the dataset using the shapefile
    clipped_ds = ds.rio.clip(gdf.geometry.values, gdf.crs, drop=True, all_touched=True)

    # Save the clipped dataset as a new NetCDF file
    output_clipped_file = file.replace(".nc", ".clipped.nc")
    clipped_ds.to_netcdf(output_clipped_file)

C:\Users\sonle\AppData\Local\Temp\ipykernel_11064\578766444.py:9: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for file in tqdm_notebook(files):

  0%|          | 0/9 [00:00<?, ?it/s]

In [6]:
test = rxr.open_rasterio(r"D:\Work\WB\LDT\data\raw_data\gfdl-esm4_r1i1p1f1_w5e5_ssp585_tasmax_global_daily_2015_2020.clipped.nc")
test.sel(time='2020-01-01').rio.to_raster(r"D:\Work\WB\LDT\data\raw_data\test.tiff")

In [ ]:
# https://www.isimip.org/gettingstarted/input-data-bias-adjustment/details/84/

files = glob.glob("D:/Work/WB\LDT/data/raw_data/*clipped.nc")

combined_dataset = xr.open_mfdataset(files, combine='by_coords', parallel=False)
combined_dataset.to_netcdf("D:/Work/WB/LDT/data/raw_data/gfdl-esm4_ssp585_tasmax_global_daily_2015_2100_SRB_touched.nc")

In [9]:
import rasterio
import geopandas as gpd
from shapely.geometry import box

# Load the raster file
raster_path = r"D:\Work\WB\LDT\data\raw_data\test.tiff"
with rasterio.open(raster_path) as dataset:
    # Get the bounds of each pixel
    bounds = []
    for row in range(dataset.height):
        for col in range(dataset.width):
            # Get the pixel bounds
            pixel_bounds = dataset.window_bounds(((row, row + 1), (col, col + 1)))
            bounds.append(box(*pixel_bounds))
    
    # Create a GeoDataFrame from the bounds
    gdf = gpd.GeoDataFrame(geometry=gpd.GeoSeries(bounds), crs=dataset.crs)
gdf = gdf.sjoin(poly).drop(['index_right', 'GID_0', 'COUNTRY'], axis=1).reset_index(drop=True)
gdf['GRID_N'] = gdf.index
# Save the GeoDataFrame as a GeoJSON file
output_json_path = r"D:\Work\WB\LDT\data\raw_data\pixels.json"
gdf[['GRID_N', 'geometry']].to_file(output_json_path, driver='GeoJSON', index=False)

In [10]:
import sys
sys.path.append('D:\Work\WB\LDT')
from src.dhelper import *
from rasterstats import zonal_stats
import concurrent 

dates = get_daterange('2023-01-01', '2100-12-31', 
              input_format='%Y-%m-%d',
              output_format='%Y-%m-%d')

In [11]:
ds = xr.open_dataset("D:/Work/WB/LDT/data/raw_data/gfdl-esm4_ssp585_tasmax_global_daily_2015_2100_SRB_touched.nc")
pixels = gpd.read_file(r"D:\Work\WB\LDT\data\raw_data\pixels.json")

tasmax = ds['tasmax']
affine = tasmax.rio.transform()
grids = pixels['GRID_N'].to_list()

dfs = []

for date in tqdm_notebook(dates[:]):
    tm_d = tasmax.sel(time=date)
    stats = zonal_stats(pixels.geometry, tm_d.values, affine=affine, stats=['mean'])
    df = pd.DataFrame(stats)
    df['date'] = date
    df['GRID_N'] = grids
    dfs.append(df)

C:\Users\sonle\AppData\Local\Temp\ipykernel_7240\1157600090.py:10: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for date in tqdm_notebook(dates[:]):

  0%|          | 0/28489 [00:00<?, ?it/s]

c:\Users\sonle\anaconda3\envs\wb-ldt\Lib\site-packages\rasterstats\io.py:328: NodataWarning: Setting nodata to -999; specify nodata explicitly
  warnings.warn(

In [ ]:
# def calc_zonal_heat(ds, poly, affine, date):
#     tm_d = ds.sel(time=date)
#     stats = zonal_stats(poly.geometry, tm_d.values, affine=affine, stats=['mean'])
#     df = pd.DataFrame(stats)
#     df['date'] = date
#     df['GRID_N'] = poly['GRID_N'].to_list()
#     return df

# with concurrent.futures.ThreadPoolExecutor(max_workers=8) as executor:
#     futures = [executor.submit(calc_zonal_heat, tasmax, pixels, affine, date) for date in dates]

In [12]:
df_tasmax = pd.concat(dfs, axis=0).reset_index(drop=True)
df_tasmax['date'] = pd.to_datetime(df_tasmax['date'])

In [13]:
def count_consecutive_exceedances_all_grids(df, temp_threshold, n_days):
    """
    Counts the number of times the temperature exceeds the specified threshold for n consecutive days 
    for each grid in the DataFrame.

    Parameters:
        df (pd.DataFrame): DataFrame containing "mean", "date", and "grid_n" columns.
        temp_threshold (float): The temperature threshold to compare against.
        n_days (int): The number of consecutive days the temperature should exceed the threshold.

    Returns:
        pd.DataFrame: DataFrame with grid numbers and their corresponding exceedance counts.
    """
    # Initialize an empty list to store results
    results = []

    # Loop through each unique grid number
    for grid in df['GRID_N'].unique():
        # Filter the data for the current grid
        df_grid = df[df['GRID_N'] == grid]
        
        # Sort the DataFrame by date to ensure we are checking consecutive days in order
        df_grid = df_grid.sort_values(by='date')
        
        # Create a boolean mask where temperature exceeds the threshold
        exceed_mask = df_grid['mean'] > temp_threshold + 273.15
        
        # Initialize the count of exceedances
        exceedance_count = 0
        
        # Initialize a counter to track consecutive exceedances
        consecutive_days = 0
        
        # Loop through the boolean mask
        for exceeded in exceed_mask:
            if exceeded:
                # If the temperature exceeded the threshold, increase consecutive count
                consecutive_days += 1
            else:
                # If it didn't exceed, reset the consecutive count
                consecutive_days = 0
            
            # Check if we've reached the required number of consecutive days
            if consecutive_days >= n_days:
                exceedance_count += 1
                # Reset the consecutive days count to avoid double-counting overlapping periods
                consecutive_days = 0
        
        # Append the result for the current grid
        results.append({'GRID_N': grid, 'exceedance_count': exceedance_count})
    
    # Convert results to a DataFrame
    return pd.DataFrame(results)

In [14]:
result_df = count_consecutive_exceedances_all_grids(df_tasmax, temp_threshold=40, n_days=5)
result_df.head()

   GRID_N  exceedance_count
0       0                19
1       1                17
2       2                23
3       3                21
4       4                24

In [15]:
df_tasmax.to_csv("D:/Work/WB/LDT/countries/SRB/raw_data/SRB_tasmax_full.csv", index=False)

In [16]:
import ee
import geemap
ee.Authenticate()
ee.Initialize()

In [17]:
muni = gpd.read_file('D:\Work\WB\LDT\countries\SRB\shapefiles\gadm41_SRB_2.json')

rails_dfs = []
roads_dfs = []

for year in tqdm_notebook(range(2020, 2025, 1)):
    rails = gpd.read_file(f'D:/Work/WB/LDT/countries/SRB/shapefiles/rails_intersect_{year}.json')
    rails = gpd.overlay(rails, pixels, how='intersection')
    rails = rails.merge(result_df, on=['GRID_N'], how='left')
    rails = rails[rails['exceedance_count'] > 0]
    rails_km = rails.to_crs(epsg=3857)
    rails_km['rail_length_km'] = rails_km.length / 1000
    rails_sum = rails_km.groupby(['GID_2']).agg({'rail_length_km': 'sum'}).reset_index()
    rails_sum = pd.merge(muni[['GID_2']], rails_sum, on=['GID_2'], how='left')
    rails_sum['rail_length_km'] = rails_sum['rail_length_km'].fillna(0)
    rails_sum['year'] = year
    rails_dfs.append(rails_sum)

    roads = gpd.read_file(f'D:/Work/WB/LDT/countries/SRB/shapefiles/roads_intersect_{year}.json')
    roads = gpd.overlay(roads, pixels, how='intersection')
    roads = roads.merge(result_df, on=['GRID_N'], how='left')
    roads = roads[roads['exceedance_count'] > 0]
    roads_km = roads.to_crs(epsg=3857)
    roads_km['road_length_km'] = roads_km.length / 1000
    roads_sum = roads_km.groupby(['GID_2']).agg({'road_length_km': 'sum'}).reset_index()
    roads_sum = pd.merge(muni[['GID_2']], roads_sum, on=['GID_2'], how='left')
    roads_sum['road_length_km'] = roads_sum['road_length_km'].fillna(0)
    roads_sum['year'] = year
    roads_dfs.append(roads_sum)

C:\Users\sonle\AppData\Local\Temp\ipykernel_7240\1145793930.py:6: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for year in tqdm_notebook(range(2020, 2025, 1)):

  0%|          | 0/5 [00:00<?, ?it/s]

C:\Users\sonle\AppData\Local\Temp\ipykernel_7240\1145793930.py:20: UserWarning: `keep_geom_type=True` in overlay resulted in 1 dropped geometries of different geometry types than df1 has. Set `keep_geom_type=False` to retain all geometries
  roads = gpd.overlay(roads, pixels, how='intersection')
C:\Users\sonle\AppData\Local\Temp\ipykernel_7240\1145793930.py:20: UserWarning: `keep_geom_type=True` in overlay resulted in 1 dropped geometries of different geometry types than df1 has. Set `keep_geom_type=False` to retain all geometries
  roads = gpd.overlay(roads, pixels, how='intersection')

In [23]:
df_rails = pd.concat(rails_dfs, axis=0).reset_index(drop=True)
df_roads = pd.concat(roads_dfs, axis=0).reset_index(drop=True)

In [24]:
heatwave_df = pd.merge(df_rails, df_roads, on=['GID_2', 'year'], how='left')
heatwave_df = heatwave_df.rename({'rail_length_km': 'rail_length_heatwave_risk',
                                  'road_length_km': 'road_length_heatwave_risk'})

In [19]:
poly = gpd.read_file('D:\Work\WB\LDT\countries\SRB\shapefiles\gadm41_SRB_2.json')
poly = poly.to_crs(epsg=4326)
gid_2 = poly['GID_2'].to_list()
pop_stats = []

# Define the dataset collection
# https://developers.google.com/earth-engine/datasets/catalog/WRI_Aqueduct_Flood_Hazard_Maps_V2#image-properties
# https://files.wri.org/d8/s3fs-public/aqueduct-floods-methodology.pdf?_gl=1*1u9ay0w*_gcl_au*MTg3NzAwNTI0OC4xNzI0MjQwNTIw
# https://www.usgs.gov/centers/new-jersey-water-science-center/floods-recurrence-intervals-and-100-year-floods 
pops = ee.ImageCollection("projects/sat-io/open-datasets/ORNL/LANDSCAN_GLOBAL").filterDate('2022-01-01', '2022-12-31')\
                                                         .sum()\
                                                         .select('b1')

for i in tqdm_notebook(range(len(poly))):

    r = poly.iloc[i:i+1]
    region = geemap.gdf_to_ee(r).geometry()

    stats = pops.reduceRegion(
                      geometry=region,
                      reducer=ee.Reducer.sum(),
                      scale=1000,  
                      crs='EPSG:4326', 
                      tileScale=14,
                      bestEffort=True
                )
    
    
    try:
        pop = stats.getInfo()['b1']
        pop_stats.append(pop)
        
    except Exception as e:
         print(e)
         continue
    
pop_df = pd.DataFrame({'GID_2': gid_2,
                       'population_sum': pop_stats})

C:\Users\sonle\AppData\Local\Temp\ipykernel_7240\1834429226.py:14: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for i in tqdm_notebook(range(len(poly))):

  0%|          | 0/161 [00:00<?, ?it/s]

In [25]:
heatwave_df = pd.merge(heatwave_df, pop_df, on=['GID_2'], how='left')
heatwave_df['rail_length_heatwave_pcap'] = 1000*heatwave_df['rail_length_km'] / heatwave_df['population_sum']
heatwave_df['road_length_heatwave_pcap'] = 1000*heatwave_df['road_length_km'] / heatwave_df['population_sum']
heatwave_df

,GID_2,rail_length_km,year,road_length_km,population_sum,rail_length_heatwave_pcap,road_length_heatwave_pcap
0,SRB.1.1_1,88.100593,2020,1160.428311,36938.533333,2.385059,31.415116
1,SRB.1.2_1,0.000000,2020,1153.665030,16626.023529,0.000000,69.389113
2,SRB.1.3_1,47.678111,2020,905.045916,13804.294118,3.453861,65.562636
3,SRB.1.4_1,79.345232,2020,1683.561163,28860.266667,2.749290,58.334914
4,SRB.2.1_1,9.673411,2020,418.652736,6490.898039,1.490304,64.498430
...,...,...,...,...,...,...,...
800,SRB.25.6_1,53.102974,2024,1224.665836,27803.866667,1.909913,44.046602
801,SRB.25.7_1,2.464240,2024,508.443447,17834.627451,0.138172,28.508779
802,SRB.25.8_1,62.496031,2024,1996.859270,25052.764706,2.494576,79.706144
803,SRB.25.9_1,9.731242,2024,2187.686259,24215.105882,0.401867,90.343865
804,SRB.25.10_1,9.149552,2024,377.195669,55130.176471,0.165963,6.841909

In [26]:
heatwave_df.to_csv("D:/Work/WB/LDT/countries/SRB/datasets/SRB_heatwave_risk_full.csv", index=False)

In [ ]:
# rails = gpd.read_file("D:\Work\WB\LDT\countries\SRB\\raw_data\serbia-230101-free.shp\gis_osm_railways_free_1.shp")
rails = gpd.read_file('D:\Work\WB\LDT\countries\SRB\shapefiles/rails_intersect.json')

rails = gpd.overlay(rails, pixels, how='intersection')

# rails = rails.sjoin(pixels).drop(['index_right'], axis=1)
rails = rails.merge(result_df, on=['GRID_N'], how='left')
# rails = rails.sjoin(muni[['GID_2', 'geometry']]).drop(['index_right'], axis=1)
rails = rails[rails['exceedance_count'] > 0]
rails_km = rails.to_crs(epsg=3857)
rails_km['rail_length_km'] = rails_km.length / 1000
rails_sum = rails_km.groupby(['GID_2']).agg({'rail_length_km': 'sum'}).reset_index()
rails_sum = pd.merge(muni[['GID_2']], rails_sum, on=['GID_2'], how='left')
rails_sum['rail_length_km'] = rails_sum['rail_length_km'].fillna(0)
rails_sum['year'] = 2022 
rails_sum

           GID_2  rail_length_km  year
0      SRB.1.1_1       90.177980  2022
1      SRB.1.2_1        0.000000  2022
2      SRB.1.3_1       47.672230  2022
3      SRB.1.4_1       80.738326  2022
4      SRB.2.1_1       12.167753  2022
..           ...             ...   ...
156   SRB.25.6_1       54.159879  2022
157   SRB.25.7_1        2.464240  2022
158   SRB.25.8_1       62.496031  2022
159   SRB.25.9_1        9.731242  2022
160  SRB.25.10_1        9.149609  2022

[161 rows x 3 columns]

In [ ]:
rails_sum['rail_length_km'].sum()

np.float64(6737.45937923517)

In [ ]:

rails_sum.to_csv("D:\Work\WB\LDT\countries\SRB\datasets\SRB_heatwave_risk_rails_2022.csv", index=False)

In [ ]:
roads = gpd.read_file(r'D:\Work\WB\LDT\countries\SRB\shapefiles/roads_intersect.json')
# roads = roads[~roads['fclass'].isin(['cycleway', 'unknown', 'footway', 'pedestrian', 'steps', 'path', 'track_grade2', 'track_grade3', 'track_grade4', 'track_grade5', 'bridleway'])]
muni = gpd.read_file('D:\Work\WB\LDT\countries\SRB\shapefiles\gadm41_SRB_2.json')

# roads = roads.sjoin(pixels).drop(['index_right'], axis=1)
roads = gpd.overlay(roads, pixels, how='intersection')

roads = roads.merge(result_df, on=['GRID_N'], how='left')
# roads = roads.sjoin(muni[['GID_2', 'geometry']]).drop(['index_right'], axis=1)
roads = roads[roads['exceedance_count'] > 0]
roads_km = roads.to_crs(epsg=3857)
roads_km['road_length_km'] = roads_km.length / 1000
roads_sum = roads_km.groupby(['GID_2']).agg({'road_length_km': 'sum'}).reset_index()
roads_sum = pd.merge(muni[['GID_2']], roads_sum, on=['GID_2'], how='left')
roads_sum['road_length_km'] = roads_sum['road_length_km'].fillna(0)
roads_sum['year'] = 2022 
roads_sum

C:\Users\sonle\AppData\Local\Temp\ipykernel_7036\4185602065.py:6: UserWarning: `keep_geom_type=True` in overlay resulted in 1 dropped geometries of different geometry types than df1 has. Set `keep_geom_type=False` to retain all geometries
  roads = gpd.overlay(roads, pixels, how='intersection')

           GID_2  road_length_km  year
0      SRB.1.1_1     2507.180571  2022
1      SRB.1.2_1     1257.205849  2022
2      SRB.1.3_1     1933.827614  2022
3      SRB.1.4_1     2503.502281  2022
4      SRB.2.1_1      768.621327  2022
..           ...             ...   ...
156   SRB.25.6_1     1223.957366  2022
157   SRB.25.7_1      477.134555  2022
158   SRB.25.8_1     1964.716982  2022
159   SRB.25.9_1     2153.096784  2022
160  SRB.25.10_1      376.808285  2022

[161 rows x 3 columns]

In [ ]:
roads_sum['road_length_km'].sum()

np.float64(251530.9253225514)

In [ ]:
heatwave_df = pd.merge(rails_sum, roads_sum, on=['GID_2', 'year'], how='left')
heatwave_df = heatwave_df.rename({'rail_length_km': 'rail_length_heatwave_risk',
                                  'road_length_km': 'road_length_heatwave_risk'})
heatwave_df.to_csv("D:\Work\WB\LDT\countries\SRB\datasets\SRB_heatwave_risk_2022.csv", index=False)

Successfully saved authorization token.

In [ ]:
poly = gpd.read_file('D:\Work\WB\LDT\countries\SRB\shapefiles\gadm41_SRB_2.json')
poly = poly.to_crs(epsg=4326)
gid_2 = poly['GID_2'].to_list()
pop_stats = []

# Define the dataset collection
# https://developers.google.com/earth-engine/datasets/catalog/WRI_Aqueduct_Flood_Hazard_Maps_V2#image-properties
# https://files.wri.org/d8/s3fs-public/aqueduct-floods-methodology.pdf?_gl=1*1u9ay0w*_gcl_au*MTg3NzAwNTI0OC4xNzI0MjQwNTIw
# https://www.usgs.gov/centers/new-jersey-water-science-center/floods-recurrence-intervals-and-100-year-floods 
pops = ee.ImageCollection("projects/sat-io/open-datasets/ORNL/LANDSCAN_GLOBAL").filterDate('2022-01-01', '2022-12-31')\
                                                         .sum()\
                                                         .select('b1')

for i in tqdm_notebook(range(len(poly))):

    r = poly.iloc[i:i+1]
    region = geemap.gdf_to_ee(r).geometry()

    stats = pops.reduceRegion(
                      geometry=region,
                      reducer=ee.Reducer.sum(),
                      scale=1000,  
                      crs='EPSG:4326', 
                      tileScale=14,
                      bestEffort=True
                )
    
    
    try:
        pop = stats.getInfo()['b1']
        pop_stats.append(pop)
        
    except Exception as e:
         print(e)
         continue
    
pop_df = pd.DataFrame({'GID_2': gid_2,
                       'population_sum': pop_stats})
pop_df['year'] = 2022

C:\Users\sonle\AppData\Local\Temp\ipykernel_34484\3522453047.py:14: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for i in tqdm_notebook(range(len(poly))):

  0%|          | 0/161 [00:00<?, ?it/s]

In [ ]:
pop_df

           GID_2  population_sum  year
0      SRB.1.1_1    36938.533333  2022
1      SRB.1.2_1    16626.023529  2022
2      SRB.1.3_1    13804.294118  2022
3      SRB.1.4_1    28860.266667  2022
4      SRB.2.1_1     6490.898039  2022
..           ...             ...   ...
156   SRB.25.6_1    27803.866667  2022
157   SRB.25.7_1    17834.627451  2022
158   SRB.25.8_1    25052.764706  2022
159   SRB.25.9_1    24215.105882  2022
160  SRB.25.10_1    55130.176471  2022

[161 rows x 3 columns]

In [ ]:
heatwave_df = pd.merge(heatwave_df, pop_df, on=['GID_2', 'year'], how='left')
heatwave_df['rail_length_heatwave_pcap'] = 1000*heatwave_df['rail_length_km'] / heatwave_df['population_sum']
heatwave_df['road_length_heatwave_pcap'] = 1000*heatwave_df['road_length_km'] / heatwave_df['population_sum']
heatwave_df

,GID_2,rail_length_km,year,road_length_km,population_sum,rail_length_heatwave_pcap,road_length_heatwave_pcap
0,SRB.1.1_1,91.160238,2022,2990.901095,36938.533333,2.467890,80.969677
1,SRB.1.2_1,0.000000,2022,1389.346154,16626.023529,0.000000,83.564549
2,SRB.1.3_1,48.239500,2022,2155.660005,13804.294118,3.494529,156.158655
3,SRB.1.4_1,85.573661,2022,2562.409002,28860.266667,2.965103,88.786740
4,SRB.2.1_1,19.811233,2022,825.662548,6490.898039,3.052156,127.203130
...,...,...,...,...,...,...,...
156,SRB.25.6_1,60.207639,2022,1495.303792,27803.866667,2.165441,53.780426
157,SRB.25.7_1,5.383156,2022,616.241730,17834.627451,0.301837,34.553104
158,SRB.25.8_1,63.383139,2022,2052.946448,25052.764706,2.529986,81.944906
159,SRB.25.9_1,10.862056,2022,2428.834177,24215.105882,0.448565,100.302439
160,SRB.25.10_1,11.091691,2022,423.071370,55130.176471,0.201191,7.674043

In [ ]:
heatwave_df[['GID_2', 'year', 'rail_length_heatwave_pcap', 'road_length_heatwave_pcap']].to_csv("D:\Work\WB\LDT\countries\SRB\datasets\SRB_heatwave_risk_2022.csv", index=False)

In [ ]:
heatwave_df.describe()

,rail_length_km,year,road_length_km,population_sum,rail_length_heatwave_pcap,road_length_heatwave_pcap
count,161.000000,161.0,161.000000,161.000000,161.000000,161.000000
mean,63.074638,2022.0,1746.835474,36592.626647,2.074441,84.254317
std,80.470502,0.0,1058.357529,52658.708031,2.608554,68.106141
min,0.000000,2022.0,0.000000,937.603922,0.000000,0.000000
25%,0.000000,2022.0,1024.966369,11576.000000,0.000000,42.591364
50%,42.974898,2022.0,1475.852388,21012.349020,1.222259,76.646853
75%,89.739146,2022.0,2375.754440,39362.850980,3.075098,107.552932
max,467.915560,2022.0,5363.075450,456825.266667,16.753582,648.933669

# GED

In [ ]:
import os
import sys
sys.path.append(os.path.dirname(os.getcwd()))
from src.dhelper import *
import xarray as xr
import rioxarray as rxr
import rasterio
from tqdm import tqdm_notebook

In [ ]:
import ee

try:
    ee.Initialize(project='bigdataobservatory-363204')
except Exception as e:
    ee.Authenticate()
    ee.Initialize(project='bigdataobservatory-363204')

*** Earth Engine *** Share your feedback by taking our Annual Developer Satisfaction Survey: https://google.qualtrics.com/jfe/form/SV_0JLhFqfSY1uiEaW?source=Init

In [ ]:
# dates = get_daterange('2000-01-01', '2002-12-30', input_format='%Y-%m-%d', output_format='%Y-%m-%d')
dates = get_daterange('2018-01-01', '2022-12-30', input_format='%Y-%m-%d', output_format='%Y-%m-%d')
country = 'BTN'

In [ ]:
region = ee.FeatureCollection("FAO/GAUL/2015/level2").filter(ee.Filter.inList('ADM0_NAME', ['Bhutan'])).geometry()

for date in tqdm_notebook(dates):
    dataset = ee.ImageCollection('ECMWF/ERA5_LAND/HOURLY')\
                .filterDate(f"{date}T00:00:00", f"{date}T23:59:59")
    
    avg_temp = dataset.select('temperature_2m').mean().subtract(273.15).rename('avg_temp')
    max_temp = dataset.select('temperature_2m').max().subtract(273.15).rename('max_temp')

    total_precipitation = dataset.select('total_precipitation').sum().rename('precipitation')

    combined = avg_temp.addBands(max_temp).addBands(total_precipitation)

    task = ee.batch.Export.image.toDrive(image=combined,
                                     description=f'era5_{country}_{date}',
                                     scale=11132,
                                     region=region,
                                     folder=f'era5',
                                     fileNamePrefix=f'{country}_era5_{date}',
                                     crs='EPSG:4326',
                                     fileFormat='GeoTIFF')
    task.start()

C:\Users\sonle\AppData\Local\Temp\ipykernel_19912\1502872715.py:3: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for date in tqdm_notebook(dates):

  0%|          | 0/1825 [00:00<?, ?it/s]

In [ ]:
dates = get_daterange('2006-01-01', '2010-12-31', input_format='%Y-%m-%d', output_format='%Y-%m-%d')
region = ee.FeatureCollection("FAO/GAUL/2015/level2").filter(ee.Filter.inList('ADM0_NAME', ['Bhutan'])).geometry()

for date in tqdm_notebook(dates):
    dataset = ee.ImageCollection('ECMWF/ERA5_LAND/HOURLY')\
                .filterDate(f"{date}T00:00:00", f"{date}T23:59:59")
    
    avg_temp = dataset.select('temperature_2m').mean().subtract(273.15).rename('avg_temp')
    max_temp = dataset.select('temperature_2m').max().subtract(273.15).rename('max_temp')

    total_precipitation = dataset.select('total_precipitation').sum().rename('precipitation')

    combined = avg_temp.addBands(max_temp).addBands(total_precipitation)

    task = ee.batch.Export.image.toDrive(image=combined,
                                     description=f'era5_{country}_{date}',
                                     scale=11132,
                                     region=region,
                                     folder=f'era5',
                                     fileNamePrefix=f'{country}_era5_{date}',
                                     crs='EPSG:4326',
                                     fileFormat='GeoTIFF')
    task.start()

C:\Users\sonle\AppData\Local\Temp\ipykernel_19616\1941330839.py:4: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for date in tqdm_notebook(dates):

  0%|          | 0/1826 [00:00<?, ?it/s]